#!/bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

. /usr/lib/init/dropbear.sh

gen_key() {
	key_type=$1
	key_file=$2

	[ -e "$key_file" ] && return

	rm -f $key_file > /dev/null 2>&1

	echo -n "generating $key_type key..."
	dropbearkey -t $key_type -f $key_file > /dev/null 2>&1

	if [ "$?" = "0" ]; then
		echo "done"
	else
		echo "failed"
		exit 1
	fi
}

gen_keys() {
	for keytype in $DROPBEAR_KEYTYPES
	do
		case "$keytype" in
			rsa)
				gen_key rsa "$DROPBEAR_RSAKEY"
				;;
			ecdsa)
				gen_key ecdsa "$DROPBEAR_ECDSAKEY"
				;;
			*)
				echo "Key type '$keytype' not supported"
				;;
		esac
	done
}

if ! gen_keys
then
	echo "Generating SSH keys failed!"
	exit 1
fi
