#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

get_hostkeys() {
	[ -f /etc/ssh/sshd_config ] || return
	sed -n 's/^HostKey[ \t][ \t]*\(.*\)/\1/p' /etc/ssh/sshd_config
}

host_keys_required() {
	hostkeys="$(get_hostkeys)"
	if [ "$hostkeys" ]; then
		echo "$hostkeys"
	else
		# No HostKey directives found, so we pick secure defaults
		echo /etc/ssh/ssh_host_ed25519_key
	fi
}

create_key() {
	keytype="$1"
	shift
	hostkeys="$1"
	shift

	file="/etc/ssh/ssh_host_${keytype}_key"

	if echo "$hostkeys" | grep -x -F "$file" >/dev/null; then
		echo "Create $keytype key; this may take some time ..."
		rm -f $file &&
		ssh-keygen -q -f "$file" -N '' -t "$keytype" "$@" || return
		echo "Created $keytype key."
	fi
}

create_keys() {
	hostkeys="$(host_keys_required)"

	create_key "dsa" "$hostkeys" &&
	create_key "ecdsa" "$hostkeys" &&
	create_key "ed25519" "$hostkeys" &&
	create_key "rsa" "$hostkeys" -b 4096
}

if ! create_keys; then
	echo "Generating SSH keys failed!"
	exit 1
fi
