#!/bin/sh

WRAPPER_DIR="$(dirname "$(readlink -f "$0")")"
. "${WRAPPER_DIR}/libwrapper.sh" || exit

cc_check_args "${@}"

cc_add_target_reproducible
cxx_add_target_extra
cc_add_target_ld_args
cc_add_fortify
cc_add_stack
cc_add_pie
cc_add_glibcxx
cxx_add_target_icecc

wrapper_exec "$@"
