#!/bin/sh

WRAPPER_DIR="$(dirname "$(readlink -f "$0")")"
. "${WRAPPER_DIR}/libwrapper.sh" || exit

HOST=true

cc_check_args "${@}"

LINKING=false
unset PTXDIST_CCACHE

cpp_add_host_extra

wrapper_exec "$@"
