#!/bin/sh

. "$(dirname "$(readlink -f "$0")")/libwrapper.sh" || exit

HOST=true

cc_check_args "${@}"

cc_add_host_clang
cc_add_host_ld_args
cc_add_host_extra
clang_check_host_icecc
cc_add_host_icecc clang

wrapper_exec "$@"
