# -*-makefile-*-
#
# Copyright (C) 2025 by Sven Püschel <s.pueschel@pengutronix.de>
#
# For further information about the PTXdist project and license conditions
# see the README file.
#

#
# We provide this package
#
HOST_PACKAGES-$(PTXCONF_HOST_LIBSOLV) += host-libsolv

HOST_LIBSOLV_CONF_TOOL	:= cmake
HOST_LIBSOLV_CONF_OPT	:= \
	$(HOST_CMAKE_OPT) \
	-DDISABLE_SHARED=OFF \
	-DENABLE_APK=OFF \
	-DENABLE_APPDATA=OFF \
	-DENABLE_ARCHREPO=OFF \
	-DENABLE_BZIP2_COMPRESSION=OFF \
	-DENABLE_COMPS=OFF \
	-DENABLE_CONDA=OFF \
	-DENABLE_CUDFREPO=OFF \
	-DENABLE_DEBIAN=OFF \
	-DENABLE_HAIKU=OFF \
	-DENABLE_HELIXREPO=OFF \
	-DENABLE_LUA=OFF \
	-DENABLE_LZMA_COMPRESSION=OFF \
	-DENABLE_MDKREPO=OFF \
	-DENABLE_PERL=OFF \
	-DENABLE_PUBKEY=OFF \
	-DENABLE_PYTHON=OFF \
	-DENABLE_RPMDB=OFF \
	-DENABLE_RPMDB_BDB=OFF \
	-DENABLE_RPMDB_BYRPMHEADER=OFF \
	-DENABLE_RPMDB_LIBRPM=OFF \
	-DENABLE_RPMMD=OFF \
	-DENABLE_RPMPKG=OFF \
	-DENABLE_RPMPKG_LIBRPM=OFF \
	-DENABLE_RUBY=OFF \
	-DENABLE_STATIC=OFF \
	-DENABLE_STATIC_BINDINGS=OFF \
	-DENABLE_STATIC_TOOLS=OFF \
	-DENABLE_SUSEREPO=OFF \
	-DENABLE_TCL=OFF \
	-DENABLE_ZCHUNK_COMPRESSION=OFF \
	-DENABLE_ZSTD_COMPRESSION=OFF \
	-DMULTI_SEMANTICS=ON \
	-DUSE_VENDORDIRS=OFF \
	-DWITHOUT_COOKIEOPEN=OFF \
	-DWITH_LIBXML2=OFF \
	-DWITH_SYSTEM_ZCHUNK=OFF

# vim: syntax=make
