# -*-makefile-*-
#
# Copyright (C) 2023 by Michael Olbrich <m.olbrich@pengutronix.de>
#
# For further information about the PTXdist project and license conditions
# see the README file.
#

#
# We provide this package
#
HOST_PACKAGES-$(PTXCONF_HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS) += host-system-python3-pyproject-hooks

#
# Paths and names
#
HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS_VERSION		= $(HOST_PYTHON3_PYPROJECT_HOOKS_VERSION)
HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS_MD5		= $(HOST_PYTHON3_PYPROJECT_HOOKS_MD5)
HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS			= system-$(HOST_PYTHON3_PYPROJECT_HOOKS)
HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS_SUFFIX		= $(HOST_PYTHON3_PYPROJECT_HOOKS_SUFFIX)
HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS_URL		= $(HOST_PYTHON3_PYPROJECT_HOOKS_URL)
HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS_SOURCE		= $(HOST_PYTHON3_PYPROJECT_HOOKS_SOURCE)
HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS_DIR		= $(HOST_BUILDDIR)/$(HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS)
HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS_LICENSE		= $(HOST_PYTHON3_PYPROJECT_HOOKS_LICENSE)
HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS_LICENSE_FILES	= $(HOST_PYTHON3_PYPROJECT_HOOKS_LICENSE_FILES)

# ----------------------------------------------------------------------------
# Prepare
# ----------------------------------------------------------------------------

HOST_SYSTEM_PYTHON3_PYPROJECT_HOOKS_CONF_TOOL	:= python3

# vim: syntax=make
